LMS/urls.py
from account.views import SignupView, LogoutView, ConfirmEmailView, ChangePasswordView, PasswordResetView, \
    PasswordResetTokenView, SettingsView, DeleteView
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from LMS import views

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include([
        url(r'^misc/', admin.site.urls),
        url(r'^', include('LMS_Admin.urls')),
    ])),
    url(r"^stu/", include("LMS_Student.urls")),
    url(r"^lec/", include("LMS_Teacher.urls")),
    url(r"^account/", include([
        url(r"^signup/$", SignupView.as_view(), name="account_signup"),
        url(r"^login/$", views.LoginView.as_view(), name="account_login"),
        url(r"^logout/$", LogoutView.as_view(), name="account_logout"),
        url(r"^confirm_email/(?P<key>\w+)/$", ConfirmEmailView.as_view(), name="account_confirm_email"),
        url(r"^password/$", ChangePasswordView.as_view(), name="account_password"),
        url(r"^password/reset/$", PasswordResetView.as_view(), name="account_password_reset"),
        url(r"^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$", PasswordResetTokenView.as_view(),
            name="account_password_reset_token"),
        url(r"^settings/$", SettingsView.as_view(), name="account_settings"),
        url(r"^delete/$", DeleteView.as_view(), name="account_delete"),
    ])),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

LMS_Teacher/urls.py
from django.conf.urls import include, url
from django.views.generic import RedirectView

from LMS_Teacher import views

app_name = 'lms_tec'

urlpatterns = [
    url(r'^$', views.PersonalInfoView.as_view(), name='home'),
    url(r'^my_units/$', views.UnitListView.as_view(), name='unit'),
    url(r"^timetable/$", views.TimetableView.as_view(), name="timetable"),
    url(r'^unit/(?P<unit_id>[0-9]+)/', include([
        url(r'^info/$', views.UnitInfoView.as_view(), name='unit_info'),
        url(r'^material/', include([
            url(r'^$', views.MaterialListView.as_view(), name='material'),
            url(r'^upload/$', views.MaterialCreateView.as_view(), name='material_upload'),
            url(r'^(?P<material_id>[0-9]+)/', include([
                url(r'^$', views.MaterialEditView.as_view(), name='material_edit'),
                url(r'^delete/$', views.MaterialDeleteView.as_view(), name='material_delete'),
            ])),
        ])),
        url(r'^assignment/', include([
            url(r'^$', views.AssignmentListView.as_view(), name='assignment'),
            url(r'^create/$', views.AssignmentCreateView.as_view(), name='assignment_create'),
            url(r'^(?P<assignment_id>[0-9]+)/', include([
                url(r'^$', views.AssignmentFileListView.as_view(), name='assignment_file'),
                url(r'^edit/$', views.AssignmentEditView.as_view(), name='assignment_edit'),
                url(r'^delete/$', views.AssignmentDeleteView.as_view(), name='assignment_delete'),
            ])),
        ])),
        url(r'^grade/', include([
            url(r'^$', views.UnitGradeView.as_view(), name='grade'),
            url(r'^edit/$', views.UnitGradeEditView.as_view(), name='grade_edit'),
            url(r'^(?P<record_id>[0-9]+)/$', views.UnitGradeMarkView.as_view(), name='grade_mark'),
        ])),
        url(r"^email/$", views.UnitEmailView.as_view(), name="email"),
    ]))
]

LMS/models.py
from decimal import Decimal
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models


# Create your models here.


class Faculty(models.Model):
    name = models.CharField(max_length=128)
    location = models.CharField(max_length=512)

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=128)
    degree = models.CharField(max_length=128)
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


GENDERS = (
    ('m', 'Male'),
    ('f', 'Female'),
)


class Student(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    gender = models.CharField(max_length=1, choices=GENDERS)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    year = models.IntegerField()
    start_date = models.DateField(auto_now=True)

    enrolled_unit = models.ManyToManyField('Unit', blank=True)

    grade = models.ManyToManyField('Unit', blank=True, through='GradeRecord', related_name='grade_record')

    def __str__(self):
        return self.user.username


TITLES = (
    ('Mr', 'Mr'),
    ('Mrs', 'Mrs'),
    ('Ms', 'Ms'),
    ('Miss', 'Miss'),
    ('Prof', 'Prof'),
    ('Dr', 'Dr'),
)


class Teacher(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    gender = models.CharField(max_length=1, choices=GENDERS)
    title = models.CharField(max_length=32, choices=TITLES)
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Unit(models.Model):
    code = models.CharField(max_length=16)
    name = models.CharField(max_length=128)
    year = models.IntegerField()
    session = models.IntegerField(choices=((1, 'S1'), (2, 'S2')))
    credit_point = models.FloatField()
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    location = models.CharField(max_length=512)

    staff = models.ManyToManyField(Teacher, through='UnitAllocation')

    mark_assignment = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_quiz = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_presentation = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_mid_exam = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_final_exam = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])

    def __str__(self):
        return '%s: %s' % (self.code, self.name)

    @property
    def total_mark(self):
        return self.mark_assignment + self.mark_quiz + \
               self.mark_presentation + self.mark_mid_exam + self.mark_final_exam


DAY_OF_WEEK = (
    (1, 'Monday'),
    (2, 'Tuesday'),
    (3, 'Wednesday'),
    (4, 'Thursday'),
    (5, 'Friday'),
    (6, 'Saturday'),
    (7, 'Sunday'),
)


class Class(models.Model):
    TYPE = (
        ('l', 'Lecture'),
        ('t', 'Tutorial'),
        ('b', 'Laboratory')
    )
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    day = models.PositiveSmallIntegerField(choices=DAY_OF_WEEK)
    start_time = models.TimeField()
    end_time = models.TimeField()
    start_week = models.PositiveSmallIntegerField()
    end_week = models.PositiveSmallIntegerField()
    type = models.CharField(max_length=1, choices=TYPE)
    location = models.CharField(max_length=128)

    @property
    def fine_str(self):
        return '{:%I:%M %p} to {:%I:%M %p}, weeks {}-{}: {} {} in {}'.format(
            self.start_time, self.end_time, self.start_week, self.end_week, self.unit.code, self.get_type_display(),
            self.location)


class UnitAllocation(models.Model):
    ROLES = (
        ('c', 'Coordinator'),
        ('l', 'Lecturer'),
        ('t', 'Tutor')
    )
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    role = models.CharField(max_length=1, choices=ROLES)

    def __str__(self):
        return '%s as %s' % (self.teacher.user.username, self.get_role_display())


class Material(models.Model):
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    uploader = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    file = models.FileField()
    upload_time = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Assignment(models.Model):
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    publish_time = models.DateTimeField(auto_now_add=True)
    due_time = models.DateTimeField()
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class AssignmentFile(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    uploader = models.ForeignKey(Student, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    file = models.FileField()
    upload_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class GradeRecord(models.Model):
    student = models.ForeignKey(Student)
    unit = models.ForeignKey(Unit)

    mark_assignment = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_quiz = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_presentation = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_mid_exam = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_final_exam = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])

    @property
    def total_mark(self):
        return self.mark_assignment + self.mark_quiz + \
               self.mark_presentation + self.mark_mid_exam + self.mark_final_exam

LMS_Teacher/models.py
from django.db import models

# Create your models here.

LMS_Teacher/forms.py
from bootstrap3_datetime.widgets import DateTimePicker
from django.utils.translation import ugettext_lazy as _
from django import forms

from LMS.models import Assignment, Unit, GradeRecord


class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ['name', 'due_time', 'description']

    def __init__(self, *args, **kwargs):
        super(AssignmentForm, self).__init__(*args, **kwargs)
        self.fields['due_time'].widget = DateTimePicker(options={"format": "YYYY-MM-DD HH:mm"})


class GradeEditForm(forms.ModelForm):
    class Meta:
        model = Unit
        fields = ['mark_assignment', 'mark_quiz', 'mark_presentation', 'mark_mid_exam', 'mark_final_exam']
        labels = {
            'mark_assignment': _('Assignment Mark'),
            'mark_quiz': _('Quiz Mark'),
            'mark_presentation': _('Presentation Mark'),
            'mark_mid_exam': _('Mid Exam Mark'),
            'mark_final_exam': _('Final Exam Mark')
        }


class GradeRecordForm(forms.ModelForm):
    class Meta:
        model = GradeRecord
        fields = ['mark_assignment', 'mark_quiz', 'mark_presentation', 'mark_mid_exam', 'mark_final_exam']
        labels = {
            'mark_assignment': _('Assignment Mark'),
            'mark_quiz': _('Quiz Mark'),
            'mark_presentation': _('Presentation Mark'),
            'mark_mid_exam': _('Mid Exam Mark'),
            'mark_final_exam': _('Final Exam Mark')
        }

    def clean(self):
        unit = self.instance.unit

        for attr in self.Meta.fields:
            _max = getattr(unit, attr)
            curr = self.cleaned_data[attr]

            if curr > _max:
                self.add_error(attr, _('Ensure this value is less than or equal to %s.') % _max)

        return self.cleaned_data

LMS_Teacher/templates/LMS_Teacher/nav_base.html
{% extends "theme_bootstrap/subnav_base.html" %}

{% load i18n %}

{% block body_class %}teacher{% endblock %}

{% block subnav %}
<div class="panel panel-default">
{#    <div class="panel-heading"><strong>{% trans "Account Management" %}</strong></div>#}
    <div class="list-group">
        <a class="list-group-item tec-info" href="{% url 'lms_tec:home' %}">
            {% trans "Personal Info" %}
        </a>
        <a class="list-group-item tec-unit" href="{% url 'lms_tec:unit' %}">
            {% trans "My Units" %}
        </a>
        <a class="list-group-item tec-timetable" href="{% url 'lms_tec:timetable' %}">
            {% trans "Timetable" %}
        </a>
    </div>
</div>
{% endblock %}

LMS_Teacher/templates/LMS_Teacher/personal_info.html
{% extends 'LMS_Teacher/nav_base.html' %}

{% load i18n %}

{% block body_class %}tec tec-info{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <table class="table table-striped">
                    <tbody>
                    <tr>
                        <td>{% trans 'Name' %}</td>
                        <td>{{ user.teacher.get_title_display }} {{ user.first_name }} {{ user.last_name }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Gender' %}</td>
                        <td>{{ user.teacher.get_gender_display }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Faculty' %}</td>
                        <td>{{ user.teacher.faculty }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

LMS_Teacher/templates/LMS_Teacher/timetable.html
{% extends 'LMS_Teacher/nav_base.html' %}

{% load i18n %}

{% block body_class %}tec tec-timetable{% endblock %}

{% block body %}
    <div class="row">
        {% include 'timetable.html' %}
    </div>
{% endblock %}

LMS_Teacher/templates/LMS_Teacher/unit.html
{% extends 'LMS_Teacher/nav_base.html' %}

{% load i18n %}

{% block body_class %}tec tec-unit{% endblock %}

{% block body %}
    {% if units %}
        <div class="row">
            <ul class="list-group">
                {% for u in units %}
                    <a href="{% url "lms_tec:unit_info" u.pk %}"
                       class="list-group-item list-group-item-action">{{ u }}</a>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

LMS_Teacher/templates/LMS_Teacher/unit_assignment.html
{% extends 'LMS_Teacher/nav_unit.html' %}

{% load i18n %}

{% block body_class %}tec tec-unit-assignment{% endblock %}

{% block body %}
    <div class="row">
        <a class="btn btn-primary" href="{% url 'lms_tec:assignment_create' unit.pk %}">{% trans "Create Assignment" %}</a>
    </div>
    {% if assignments %}
        <div class="row">
            <ul class="list-group">
                {% for a in assignments %}
                    <a href="{% url 'lms_tec:assignment_file' unit.pk a.pk %}"
                       class="list-group-item list-group-item-action">{{ a }}</a>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

LMS_Teacher/templates/LMS_Teacher/unit_assignment_delete.html
{% extends 'LMS_Teacher/nav_unit.html' %}

{% load i18n %}
{% load bootstrap %}

{% block body_class %}tec tec-unit-assignment{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-5">
            <form method="POST">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ assignment }}"?</p>
                <a class="btn btn-default pull-right"
                   href="{% url 'lms_tec:assignment_edit' unit.pk assignment.pk %}">{% trans "Cancel" %}</a>
                <button type="submit" class="btn btn-danger pull-right">{% trans "Confirm" %}</button>
            </form>
        </div>
    </div>
{% endblock %}

LMS_Teacher/templates/LMS_Teacher/unit_assignment_file.html
{% extends 'LMS_Teacher/nav_unit.html' %}

{% load i18n %}

{% block body_class %}tec tec-unit-assignment{% endblock %}

{% block body %}
    <div class="row">
        <a class="btn btn-primary" href="{% url 'lms_tec:assignment_edit' unit.pk assignment.pk %}">{% trans "Edit Assignment" %}</a>
    </div>
    {% if files %}
        <div class="row">
            <ul class="list-group">
                {% for f in files %}
                    <a href=""
                       class="list-group-item list-group-item-action">{{ f }}</a>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

LMS_Teacher/templates/LMS_Teacher/unit_email.html
{% extends 'LMS_Teacher/nav_unit.html' %}

{% load i18n %}

{% block body_class %}tec tec-unit-mail{% endblock %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        <div class="col-lg-2">
            <div class="row"><span>To:</span></div>
            {% if students %}
                <div class="checkbox">
                    {% for s in students %}
                        <div class="row">
                            <label><input type="checkbox" name="student" value="{{ s.pk }}">{{ s }}</label>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="col-lg-10">
            <div class="form-horizontal">
                <div class="form-group ">
                    <label for="subject" class="col-sm-1 control-label pull-left">{% trans 'Subject' %}</label>
                    <div class="col-sm-11">
                        <input type="text" id="subject" name="subject" class="form-control" required/>
                    </div>
                </div>
                <div class="form-group ">
                    <div class="col-sm-12">
                        <textarea name="mail_content" class="form-control" rows="20" required></textarea>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary pull-right">{% trans "Send" %}</button>
            </div>
        </div>
    </form>
{% endblock %}

LMS_Teacher/templates/LMS_Teacher/unit_grade.html
{% extends 'LMS_Teacher/nav_unit.html' %}

{% load i18n %}

{% block body_class %}tec tec-unit-grade{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th colspan="2">{% trans 'Grades' %} <a href="{% url 'lms_tec:grade_edit' unit.pk %}"
                                                                class="btn btn-default pull-right">{% trans 'Edit Grade Settings' %}</a>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>{% trans 'Assignment Mark' %}</td>
                        <td>{{ unit.mark_assignment }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Quiz Mark' %}</td>
                        <td>{{ unit.mark_quiz }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Presentation Mark' %}</td>
                        <td>{{ unit.mark_presentation }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Mid Exam Mark' %}</td>
                        <td>{{ unit.mark_mid_exam }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Final Exam Mark' %}</td>
                        <td>{{ unit.mark_final_exam }}</td>
                    </tr>
                    </tbody>
                    <tfoot>
                    <tr>
                        <th>{% trans 'Total Mark' %}</th>
                        <th>{{ unit.total_mark }}</th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th>{% trans 'Student' %}</th>
                        <th>{% trans 'Assignment' %}</th>
                        <th>{% trans 'Quiz' %}</th>
                        <th>{% trans 'Presentation' %}</th>
                        <th>{% trans 'Mid Exam' %}</th>
                        <th>{% trans 'Final Exam' %}</th>
                        <th>{% trans 'Total' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if records %}
                        {% for r in records %}
                            <tr>
                                <td><a href="{% url 'lms_tec:grade_mark' unit.pk r.pk %}"> <i
                                        class="glyphicon glyphicon-stats"></i></a></td>
                                <td>{{ r.student }}</td>
                                <td>{{ r.mark_assignment }}</td>
                                <td>{{ r.mark_quiz }}</td>
                                <td>{{ r.mark_presentation }}</td>
                                <td>{{ r.mark_mid_exam }}</td>
                                <td>{{ r.mark_final_exam }}</td>
                                <td>{{ r.total_mark }}</td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

LMS_Teacher/templates/LMS_Teacher/unit_grade_edit.html
{% extends 'LMS_Teacher/nav_unit.html' %}

{% load i18n %}
{% load bootstrap %}

{% block body_class %}tec tec-unit-grade{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-5">
            <form method="POST">
                {% csrf_token %}
                {{ form|bootstrap }}
                <a class="btn btn-default pull-right"
                   href="{% url 'lms_tec:grade' unit.pk %}">{% trans "Cancel" %}</a>
                <button type="submit" class="btn btn-primary pull-right">{% trans "Submit" %}</button>
            </form>
        </div>
    </div>
{% endblock %}

LMS_Teacher/templates/LMS_Teacher/unit_info.html
{% extends 'LMS_Teacher/nav_unit.html' %}

{% load i18n %}

{% block body_class %}tec tec-unit-info{% endblock %}

{% block body %}
    {{ unit }}
{% endblock %}

LMS_Teacher/templates/LMS_Teacher/unit_material.html
{% extends 'LMS_Teacher/nav_unit.html' %}

{% load i18n %}

{% block body_class %}tec tec-unit-material{% endblock %}

{% block body %}
    <div class="row">
        <a class="btn btn-primary" href="{% url 'lms_tec:material_upload' unit.pk %}">{% trans "Upload Material" %}</a>
    </div>
    {% if materials %}
        <div class="row">
            <ul class="list-group">
                {% for m in materials %}
                    <a href="{% url 'lms_tec:material_edit' unit.pk m.pk %}"
                       class="list-group-item list-group-item-action">{{ m }}</a>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

LMS_Teacher/templates/LMS_Teacher/unit_material_delete.html
{% extends 'LMS_Teacher/nav_unit.html' %}

{% load i18n %}
{% load bootstrap %}

{% block body_class %}tec tec-unit-material{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-5">
            <form method="POST">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ material }}"?</p>
                <a class="btn btn-default pull-right"
                   href="{% url 'lms_tec:material' unit.pk %}">{% trans "Cancel" %}</a>
                <button type="submit" class="btn btn-danger pull-right">{% trans "Confirm" %}</button>
            </form>
        </div>
    </div>
{% endblock %}

LMS_Teacher/templates/LMS_Teacher/unit_material_edit.html
{% extends 'LMS_Teacher/nav_unit.html' %}

{% load i18n %}
{% load bootstrap %}

{% block body_class %}tec tec-unit-material{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-5">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|bootstrap }}
                {% if object %}
                    <a class="btn btn-danger" href="{% url 'lms_tec:material_delete' unit.pk object.pk %}">
                        <i class="glyphicon glyphicon-trash"></i>{% trans "Delete" %}
                    </a>
                {% endif %}
                <a class="btn btn-default pull-right"
                   href="{% url 'lms_tec:material' unit.pk %}">{% trans "Cancel" %}</a>
                <button type="submit" class="btn btn-primary pull-right">{% trans "Submit" %}</button>
            </form>
        </div>
    </div>
{% endblock %}