LMS/urls.py
from account.views import SignupView, LogoutView, ConfirmEmailView, ChangePasswordView, PasswordResetView, \
    PasswordResetTokenView, SettingsView, DeleteView
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from LMS import views

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include([
        url(r'^misc/', admin.site.urls),
        url(r'^', include('LMS_Admin.urls')),
    ])),
    url(r"^stu/", include("LMS_Student.urls")),
    url(r"^lec/", include("LMS_Teacher.urls")),
    url(r"^account/", include([
        url(r"^signup/$", SignupView.as_view(), name="account_signup"),
        url(r"^login/$", views.LoginView.as_view(), name="account_login"),
        url(r"^logout/$", LogoutView.as_view(), name="account_logout"),
        url(r"^confirm_email/(?P<key>\w+)/$", ConfirmEmailView.as_view(), name="account_confirm_email"),
        url(r"^password/$", ChangePasswordView.as_view(), name="account_password"),
        url(r"^password/reset/$", PasswordResetView.as_view(), name="account_password_reset"),
        url(r"^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$", PasswordResetTokenView.as_view(),
            name="account_password_reset_token"),
        url(r"^settings/$", SettingsView.as_view(), name="account_settings"),
        url(r"^delete/$", DeleteView.as_view(), name="account_delete"),
    ])),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

LMS_Admin/urls.py
from django.conf.urls import include, url
from django.views.generic import RedirectView

from LMS_Admin import views

app_name = 'lms_admin'

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='lms_admin:account_student'), name='home'),
    url(r'^account/', include([
        url(r'^student/', include([
            url(r'^$', views.AdminStudentListView.as_view(), name='account_student'),
            url(r'^new/$', views.StudentCreateView.as_view(), name='account_student_create'),
            url(r'^(?P<pk>[0-9]+)/$', views.StudentEditView.as_view(), name='account_student_edit'),
        ])),
        url(r'^teacher/', include([
            url(r'^$', views.AdminTeacherListView.as_view(), name='account_teacher'),
            url(r'^new/$', views.TeacherCreateView.as_view(), name='account_teacher_create'),
            url(r'^(?P<pk>[0-9]+)/$', views.TeacherEditView.as_view(), name='account_teacher_edit'),
        ])),
    ])),
    url(r'^unit/', include([
        url(r'^$', views.AdminUnitListView.as_view(), name='unit'),
        url(r'^new/$', views.UnitCreateView.as_view(), name='unit_create'),
        url(r'^(?P<unit_id>[0-9]+)/', include([
            url(r'^$', views.UnitEditView.as_view(), name='unit_edit'),
            url(r'^staff/', include([
                url(r'^$', views.StaffListView.as_view(), name='unit_staff'),
                url(r'^add/$', views.StaffAddView.as_view(), name='unit_staff_add'),
                url(r'^(?P<alloc_id>[0-9]+)/', include([
                    url(r'^$', views.StaffEditView.as_view(), name='unit_staff_edit'),
                    url(r'^delete/$', views.StaffDeleteView.as_view(), name='unit_staff_delete'),
                ])),
            ])),
            url(r'^class/', include([
                url(r'^$', views.ClassListView.as_view(), name='unit_class'),
                url(r'^add/$', views.ClassAddView.as_view(), name='unit_class_add'),
                url(r'^(?P<class_id>[0-9]+)/', include([
                    url(r'^$', views.ClassEditView.as_view(), name='unit_class_edit'),
                    url(r'^delete/$', views.ClassDeleteView.as_view(), name='unit_class_delete'),
                ])),
            ])),
        ])),
    ])),
]

LMS/models.py
from decimal import Decimal
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models


# Create your models here.


class Faculty(models.Model):
    name = models.CharField(max_length=128)
    location = models.CharField(max_length=512)

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=128)
    degree = models.CharField(max_length=128)
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


GENDERS = (
    ('m', 'Male'),
    ('f', 'Female'),
)


class Student(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    gender = models.CharField(max_length=1, choices=GENDERS)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    year = models.IntegerField()
    start_date = models.DateField(auto_now=True)

    enrolled_unit = models.ManyToManyField('Unit', blank=True)

    grade = models.ManyToManyField('Unit', blank=True, through='GradeRecord', related_name='grade_record')

    def __str__(self):
        return self.user.username


TITLES = (
    ('Mr', 'Mr'),
    ('Mrs', 'Mrs'),
    ('Ms', 'Ms'),
    ('Miss', 'Miss'),
    ('Prof', 'Prof'),
    ('Dr', 'Dr'),
)


class Teacher(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    gender = models.CharField(max_length=1, choices=GENDERS)
    title = models.CharField(max_length=32, choices=TITLES)
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Unit(models.Model):
    code = models.CharField(max_length=16)
    name = models.CharField(max_length=128)
    year = models.IntegerField()
    session = models.IntegerField(choices=((1, 'S1'), (2, 'S2')))
    credit_point = models.FloatField()
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    location = models.CharField(max_length=512)

    staff = models.ManyToManyField(Teacher, through='UnitAllocation')

    mark_assignment = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_quiz = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_presentation = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_mid_exam = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_final_exam = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])

    def __str__(self):
        return '%s: %s' % (self.code, self.name)

    @property
    def total_mark(self):
        return self.mark_assignment + self.mark_quiz + \
               self.mark_presentation + self.mark_mid_exam + self.mark_final_exam


DAY_OF_WEEK = (
    (1, 'Monday'),
    (2, 'Tuesday'),
    (3, 'Wednesday'),
    (4, 'Thursday'),
    (5, 'Friday'),
    (6, 'Saturday'),
    (7, 'Sunday'),
)


class Class(models.Model):
    TYPE = (
        ('l', 'Lecture'),
        ('t', 'Tutorial'),
        ('b', 'Laboratory')
    )
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    day = models.PositiveSmallIntegerField(choices=DAY_OF_WEEK)
    start_time = models.TimeField()
    end_time = models.TimeField()
    start_week = models.PositiveSmallIntegerField()
    end_week = models.PositiveSmallIntegerField()
    type = models.CharField(max_length=1, choices=TYPE)
    location = models.CharField(max_length=128)

    @property
    def fine_str(self):
        return '{:%I:%M %p} to {:%I:%M %p}, weeks {}-{}: {} {} in {}'.format(
            self.start_time, self.end_time, self.start_week, self.end_week, self.unit.code, self.get_type_display(),
            self.location)


class UnitAllocation(models.Model):
    ROLES = (
        ('c', 'Coordinator'),
        ('l', 'Lecturer'),
        ('t', 'Tutor')
    )
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    role = models.CharField(max_length=1, choices=ROLES)

    def __str__(self):
        return '%s as %s' % (self.teacher.user.username, self.get_role_display())


class Material(models.Model):
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    uploader = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    file = models.FileField()
    upload_time = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Assignment(models.Model):
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    publish_time = models.DateTimeField(auto_now_add=True)
    due_time = models.DateTimeField()
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class AssignmentFile(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    uploader = models.ForeignKey(Student, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    file = models.FileField()
    upload_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class GradeRecord(models.Model):
    student = models.ForeignKey(Student)
    unit = models.ForeignKey(Unit)

    mark_assignment = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_quiz = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_presentation = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_mid_exam = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_final_exam = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])

    @property
    def total_mark(self):
        return self.mark_assignment + self.mark_quiz + \
               self.mark_presentation + self.mark_mid_exam + self.mark_final_exam

LMS_Admin/models.py
from django.db import models

# Create your models here.


class UidGen(models.Model):
    taken = models.BooleanField(default=True)

LMS_Admin/forms.py
from bootstrap3_datetime.widgets import DateTimePicker
from django import forms
from django.utils.translation import ugettext_lazy as _

from LMS.models import GENDERS, Course, TITLES, Faculty, Class


class DateInput(forms.DateInput):
    input_type = 'date'


class StudentEditForm(forms.Form):
    first_name = forms.CharField(max_length=30, min_length=2, label=_('First Name'), strip=True)
    last_name = forms.CharField(max_length=30, min_length=2, label=_('Last Name'), strip=True)
    gender = forms.ChoiceField(widget=forms.RadioSelect, choices=GENDERS, label=_('Gender'))
    year = forms.IntegerField(label=_('Year'))
    course = forms.ModelChoiceField(queryset=Course.objects.all(), label=_('Course'))
    start_date = forms.DateField(label=_('Start Date'), widget=DateInput())
    email = forms.EmailField(label=_('Email'))
    password = forms.CharField(label=_('Password'))


class TeacherEditForm(forms.Form):
    title = forms.ChoiceField(choices=TITLES, label=_('Title'))
    first_name = forms.CharField(max_length=30, min_length=2, label=_('First Name'), strip=True)
    last_name = forms.CharField(max_length=30, min_length=2, label=_('Last Name'), strip=True)
    gender = forms.ChoiceField(widget=forms.RadioSelect, choices=GENDERS, label=_('Gender'))
    faculty = forms.ModelChoiceField(queryset=Faculty.objects.all(), label=_('Faculty'))
    password = forms.CharField(label=_('Password'))


class ClassForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = ['day', 'start_time', 'end_time', 'start_week', 'end_week', 'type', 'location']

    def __init__(self, *args, **kwargs):
        super(ClassForm, self).__init__(*args, **kwargs)
        self.fields['start_time'].widget = DateTimePicker(options={"format": "HH:mm"},
                                                          icon_attrs={'class': 'glyphicon glyphicon-time'})
        self.fields['end_time'].widget = DateTimePicker(options={"format": "HH:mm"},
                                                        icon_attrs={'class': 'glyphicon glyphicon-time'})

    def clean(self):
        cleaned_data = super(ClassForm, self).clean()

        error = {}
        if 'start_time' in cleaned_data and 'end_time' in cleaned_data:
            if cleaned_data['start_time'] >= cleaned_data['end_time']:
                error.update({'end_time': _("End time must larger than start time.")})

        if 'start_week' in cleaned_data and 'end_week' in cleaned_data:
            if cleaned_data['start_week'] > cleaned_data['end_week']:
                error.update({'end_week': _("End week must not smaller than start week.")})
            elif cleaned_data['start_week'] <= 0:
                error.update({'start_week': _("Must larger than 0.")})

        if error:
            raise forms.ValidationError(error)

        return cleaned_data

LMS_Admin/templates/LMS_Admin/account_student.html
{% extends 'LMS_Admin/nav_base.html' %}

{% load i18n %}

{% block body_class %}admin admin-account_student{% endblock %}

{% block body %}
    <div class="row">
        <a class="btn btn-primary" href="{% url 'lms_admin:account_student_create' %}">{% trans "Create Student" %}</a>
    </div>
    {% if students %}
        <div class="row">
            <ul class="list-group">
                {% for s in students %}
                    <a href="{% url "lms_admin:account_student_edit" s.pk %}"
                       class="list-group-item list-group-item-action">{{ s }}</a>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

LMS_Admin/templates/LMS_Admin/account_student_edit.html
{% extends 'LMS_Admin/nav_base.html' %}

{% load i18n %}
{% load bootstrap %}

{% block body_class %}admin admin-account_student{% endblock %}
{% block head_title %}{{ head_title }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-5">
            <form method="POST">
                {% csrf_token %}
                {{ form|bootstrap }}
                {% if object %}
                    <a class="btn btn-danger" href="">
                        <i class="glyphicon glyphicon-trash"></i>{% trans "Delete" %}
                    </a>
                {% endif %}
                <a class="btn btn-default pull-right"
                   href="{% url 'lms_admin:account_student' %}">{% trans "Cancel" %}</a>
                <button type="submit" class="btn btn-primary pull-right">{% trans "Submit" %}</button>
            </form>
        </div>
    </div>

{% endblock %}

LMS_Admin/templates/LMS_Admin/account_teacher.html
{% extends 'LMS_Admin/nav_base.html' %}

{% load i18n %}

{% block body_class %}admin admin-account_teacher{% endblock %}

{% block body %}
    <div class="row">
        <a class="btn btn-primary" href="{% url 'lms_admin:account_teacher_create' %}">{% trans "Create Teacher" %}</a>
    </div>
    {% if teachers %}
        <div class="row">
            <ul class="list-group">
                {% for t in teachers %}
                    <a href="{% url "lms_admin:account_teacher_edit" t.pk %}"
                       class="list-group-item list-group-item-action">{{ t }}</a>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

LMS_Admin/templates/LMS_Admin/account_teacher_edit.html
{% extends 'LMS_Admin/nav_base.html' %}

{% load i18n %}
{% load bootstrap %}

{% block body_class %}admin admin-account_teacher{% endblock %}
{% block head_title %}{{ head_title }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-5">
            <form method="POST">
                {% csrf_token %}
                {{ form|bootstrap }}
                {% if object %}
                    <a class="btn btn-danger" href="">
                        <i class="glyphicon glyphicon-trash"></i>{% trans "Delete" %}
                    </a>
                {% endif %}
                <a class="btn btn-default pull-right"
                   href="{% url 'lms_admin:account_teacher' %}">{% trans "Cancel" %}</a>
                <button type="submit" class="btn btn-primary pull-right">{% trans "Submit" %}</button>
            </form>
        </div>
    </div>

{% endblock %}

LMS_Admin/templates/LMS_Admin/nav_base.html
{% extends "theme_bootstrap/subnav_base.html" %}

{% load i18n %}

{% block body_class %}admin{% endblock %}

{% block subnav %}
<div class="panel panel-default">
    <div class="panel-heading"><strong>{% trans "Account Management" %}</strong></div>
    <div class="list-group">
        <a class="list-group-item admin-account_student" href="{% url 'lms_admin:account_student' %}">
            {% trans "Student Account" %}
        </a>
        <a class="list-group-item admin-account_teacher" href="{% url 'lms_admin:account_teacher' %}">
            {% trans "Teacher Account" %}
        </a>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading"><strong>{% trans "Unit Management" %}</strong></div>
    <div class="list-group">
        <a class="list-group-item admin-units" href="{%  url 'lms_admin:unit' %}">
            {% trans "Units" %}
        </a>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading"><strong>{% trans "Miscs" %}</strong></div>
    <div class="list-group">
        <a class="list-group-item admin-misc" href="{% url 'admin:index' %}">
            {% trans "Miscs" %}
        </a>
    </div>
</div>
{% endblock %}

LMS_Admin/templates/LMS_Admin/unit.html
{% extends 'LMS_Admin/nav_base.html' %}

{% load i18n %}

{% block body_class %}admin admin-units{% endblock %}

{% block body %}
    <div class="row">
        <a class="btn btn-primary" href="{% url 'lms_admin:unit_create' %}">{% trans "Create Unit" %}</a>
    </div>
    {% if units %}
        <div class="row">
            <ul class="list-group">
                {% for u in units %}
                    <a href="{% url "lms_admin:unit_edit" u.pk %}"
                       class="list-group-item list-group-item-action">{{ u }}</a>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

LMS_Admin/templates/LMS_Admin/unit_class.html
{% extends 'LMS_Admin/nav_base.html' %}

{% load i18n %}

{% block body_class %}admin admin-units{% endblock %}

{% block body %}
    <div class="row">
        <a class="btn btn-primary" href="{% url 'lms_admin:unit_class_add' unit.pk %}">{% trans "Add Class" %}</a>
    </div>
    <table class="table table-hover table-striped">
        <thead>
        <tr>
            <th>Day of Week</th>
            <th>Time</th>
            <th>Weeks</th>
            <th>Type</th>
            <th>Location</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% if classes %}
            {% for c in classes %}
                <tr>
                    <td>{{ c.get_day_display }}</td>
                    <td>{{ c.start_time }} - {{ c.end_time }}</td>
                    <td>W{{ c.start_week }} - W{{ c.end_week }}</td>
                    <td>{{ c.get_type_display }}</td>
                    <td>{{ c.location }}</td>
                    <td><a href="{% url 'lms_admin:unit_class_edit' unit.pk c.pk %}">Edit</a></td>
                </tr>
            {% endfor %}
        {% endif %}
        </tbody>
    </table>
{% endblock %}

LMS_Admin/templates/LMS_Admin/unit_class_delete.html
{% extends 'LMS_Admin/nav_base.html' %}

{% load i18n %}
{% load bootstrap %}

{% block body_class %}admin admin-units{% endblock %}
{% block head_title %}{{ head_title }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-5">
            <form method="POST">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ class }}"?</p>
                <a class="btn btn-default pull-right"
                   href="{% url 'lms_admin:unit_class_edit' unit.pk class.pk %}">{% trans "Cancel" %}</a>
                <button type="submit" class="btn btn-danger pull-right">{% trans "Confirm" %}</button>
            </form>
        </div>
    </div>

{% endblock %}

LMS_Admin/templates/LMS_Admin/unit_class_edit.html
{% extends 'LMS_Admin/nav_base.html' %}

{% load i18n %}
{% load bootstrap %}

{% block body_class %}admin admin-units{% endblock %}
{% block head_title %}{{ head_title }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-5">
            <form method="POST">
                {% csrf_token %}
                {{ form|bootstrap }}
                {% if object %}
                    <a class="btn btn-danger" href="{% url 'lms_admin:unit_class_delete' unit.pk class.pk %}">
                        <i class="glyphicon glyphicon-trash"></i>{% trans "Delete" %}
                    </a>
                {% endif %}
                <a class="btn btn-default pull-right"
                   href="{% url 'lms_admin:unit_class' unit.pk  %}">{% trans "Cancel" %}</a>
                <button type="submit" class="btn btn-primary pull-right">{% trans "Submit" %}</button>
            </form>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    {{ block.super }}
    {{ form.media }}
{% endblock %}

LMS_Admin/templates/LMS_Admin/unit_edit.html
{% extends 'LMS_Admin/nav_base.html' %}

{% load i18n %}
{% load bootstrap %}

{% block body_class %}admin admin-units{% endblock %}
{% block head_title %}{{ head_title }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-5">
            <form method="POST">
                {% csrf_token %}
                {{ form|bootstrap }}
                {% if object %}
                    <div class="form-group">
                        <a class="btn btn-default form-control" href="{% url 'lms_admin:unit_staff' unit.pk %}">
                            <i class="glyphicon glyphicon-user"></i>{% trans "Manage Staff" %}
                        </a>
                    </div>
                    <div class="form-group">
                        <a class="btn btn-default form-control" href="{% url 'lms_admin:unit_class' unit.pk %}">
                            <i class="glyphicon glyphicon-calendar"></i>{% trans "Manage Class" %}
                        </a>
                    </div>
                {% endif %}
                <div class="form-group">
                    {% if object %}
                        <a class="btn btn-danger" href="">
                            <i class="glyphicon glyphicon-trash"></i>{% trans "Delete" %}
                        </a>
                    {% endif %}
                    <a class="btn btn-default pull-right"
                       href="{% url 'lms_admin:unit' %}">{% trans "Cancel" %}</a>
                    <button type="submit" class="btn btn-primary pull-right">{% trans "Submit" %}</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

LMS_Admin/templates/LMS_Admin/unit_staff.html
{% extends 'LMS_Admin/nav_base.html' %}

{% load i18n %}

{% block body_class %}admin admin-units{% endblock %}

{% block body %}
    <div class="row">
        <a class="btn btn-primary" href="{% url 'lms_admin:unit_staff_add' unit.pk %}">{% trans "Add Staff" %}</a>
    </div>
    {% if allocations %}
        <div class="row">
            <ul class="list-group">
                {% for alloc in allocations %}
                    <a href="{% url 'lms_admin:unit_staff_edit' unit.pk alloc.pk %}"
                       class="list-group-item list-group-item-action">{{ alloc }}</a>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

LMS_Admin/templates/LMS_Admin/unit_staff_delete.html
{% extends 'LMS_Admin/nav_base.html' %}

{% load i18n %}
{% load bootstrap %}

{% block body_class %}admin admin-units{% endblock %}
{% block head_title %}{{ head_title }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-5">
            <form method="POST">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ alloc }}"?</p>
                <a class="btn btn-default pull-right"
                   href="{% url 'lms_admin:unit_staff_edit' unit.pk alloc.pk %}">{% trans "Cancel" %}</a>
                <button type="submit" class="btn btn-danger pull-right">{% trans "Confirm" %}</button>
            </form>
        </div>
    </div>

{% endblock %}

LMS_Admin/templates/LMS_Admin/unit_staff_edit.html
{% extends 'LMS_Admin/nav_base.html' %}

{% load i18n %}
{% load bootstrap %}

{% block body_class %}admin admin-units{% endblock %}
{% block head_title %}{{ head_title }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-5">
            <form method="POST">
                {% csrf_token %}
                {{ form|bootstrap }}
                {% if object %}
                    <a class="btn btn-danger" href="{% url 'lms_admin:unit_staff_delete' unit.pk alloc.pk %}">
                        <i class="glyphicon glyphicon-trash"></i>{% trans "Delete" %}
                    </a>
                {% endif %}
                <a class="btn btn-default pull-right"
                   href="{% url 'lms_admin:unit_staff' unit.pk  %}">{% trans "Cancel" %}</a>
                <button type="submit" class="btn btn-primary pull-right">{% trans "Submit" %}</button>
            </form>
        </div>
    </div>

{% endblock %}