LMS/urls.py
from account.views import SignupView, LogoutView, ConfirmEmailView, ChangePasswordView, PasswordResetView, \
    PasswordResetTokenView, SettingsView, DeleteView
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from LMS import views

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include([
        url(r'^misc/', admin.site.urls),
        url(r'^', include('LMS_Admin.urls')),
    ])),
    url(r"^stu/", include("LMS_Student.urls")),
    url(r"^lec/", include("LMS_Teacher.urls")),
    url(r"^account/", include([
        url(r"^signup/$", SignupView.as_view(), name="account_signup"),
        url(r"^login/$", views.LoginView.as_view(), name="account_login"),
        url(r"^logout/$", LogoutView.as_view(), name="account_logout"),
        url(r"^confirm_email/(?P<key>\w+)/$", ConfirmEmailView.as_view(), name="account_confirm_email"),
        url(r"^password/$", ChangePasswordView.as_view(), name="account_password"),
        url(r"^password/reset/$", PasswordResetView.as_view(), name="account_password_reset"),
        url(r"^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$", PasswordResetTokenView.as_view(),
            name="account_password_reset_token"),
        url(r"^settings/$", SettingsView.as_view(), name="account_settings"),
        url(r"^delete/$", DeleteView.as_view(), name="account_delete"),
    ])),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

LMS_Student/urls.py
from django.conf.urls import include, url
from django.views.generic import RedirectView

from LMS_Student import views

app_name = 'lms_stu'

urlpatterns = [
    url(r'^$', views.PersonalInfoView.as_view(), name='home'),
    url(r'^my_units/$', views.UnitListView.as_view(), name='unit'),
    url(r'^enroll/$', views.EnrollListView.as_view(), name='enroll'),
    url(r"^timetable/$", views.TimetableView.as_view(), name="timetable"),
    url(r'^unit/(?P<unit_id>[0-9]+)/', include([
        url(r'^info/$', views.UnitInfoView.as_view(), name='unit_info'),
        url(r'^material/', include([
            url(r'^$', views.MaterialListView.as_view(), name='material'),
            url(r'^(?P<material_id>[0-9]+)/$', views.MaterialDownloadView.as_view(), name='material_download'),
        ])),
        url(r'^assignment/', include([
            url(r'^$', views.AssignmentListView.as_view(), name='assignment'),
            url(r'^(?P<assignment_id>[0-9]+)/', include([
                url(r'^$', views.AssignmentFileListView.as_view(), name='assignment_detail'),
                url(r'^upload/$', views.AssignmentSubmitView.as_view(), name='assignment_submit'),
            ])),
        ])),
    ])),
]

LMS/models.py
from decimal import Decimal
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models


# Create your models here.


class Faculty(models.Model):
    name = models.CharField(max_length=128)
    location = models.CharField(max_length=512)

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=128)
    degree = models.CharField(max_length=128)
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


GENDERS = (
    ('m', 'Male'),
    ('f', 'Female'),
)


class Student(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    gender = models.CharField(max_length=1, choices=GENDERS)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    year = models.IntegerField()
    start_date = models.DateField(auto_now=True)

    enrolled_unit = models.ManyToManyField('Unit', blank=True)

    grade = models.ManyToManyField('Unit', blank=True, through='GradeRecord', related_name='grade_record')

    def __str__(self):
        return self.user.username


TITLES = (
    ('Mr', 'Mr'),
    ('Mrs', 'Mrs'),
    ('Ms', 'Ms'),
    ('Miss', 'Miss'),
    ('Prof', 'Prof'),
    ('Dr', 'Dr'),
)


class Teacher(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    gender = models.CharField(max_length=1, choices=GENDERS)
    title = models.CharField(max_length=32, choices=TITLES)
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Unit(models.Model):
    code = models.CharField(max_length=16)
    name = models.CharField(max_length=128)
    year = models.IntegerField()
    session = models.IntegerField(choices=((1, 'S1'), (2, 'S2')))
    credit_point = models.FloatField()
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    location = models.CharField(max_length=512)

    staff = models.ManyToManyField(Teacher, through='UnitAllocation')

    mark_assignment = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_quiz = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_presentation = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_mid_exam = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_final_exam = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])

    def __str__(self):
        return '%s: %s' % (self.code, self.name)

    @property
    def total_mark(self):
        return self.mark_assignment + self.mark_quiz + \
               self.mark_presentation + self.mark_mid_exam + self.mark_final_exam


DAY_OF_WEEK = (
    (1, 'Monday'),
    (2, 'Tuesday'),
    (3, 'Wednesday'),
    (4, 'Thursday'),
    (5, 'Friday'),
    (6, 'Saturday'),
    (7, 'Sunday'),
)


class Class(models.Model):
    TYPE = (
        ('l', 'Lecture'),
        ('t', 'Tutorial'),
        ('b', 'Laboratory')
    )
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    day = models.PositiveSmallIntegerField(choices=DAY_OF_WEEK)
    start_time = models.TimeField()
    end_time = models.TimeField()
    start_week = models.PositiveSmallIntegerField()
    end_week = models.PositiveSmallIntegerField()
    type = models.CharField(max_length=1, choices=TYPE)
    location = models.CharField(max_length=128)

    @property
    def fine_str(self):
        return '{:%I:%M %p} to {:%I:%M %p}, weeks {}-{}: {} {} in {}'.format(
            self.start_time, self.end_time, self.start_week, self.end_week, self.unit.code, self.get_type_display(),
            self.location)


class UnitAllocation(models.Model):
    ROLES = (
        ('c', 'Coordinator'),
        ('l', 'Lecturer'),
        ('t', 'Tutor')
    )
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    role = models.CharField(max_length=1, choices=ROLES)

    def __str__(self):
        return '%s as %s' % (self.teacher.user.username, self.get_role_display())


class Material(models.Model):
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    uploader = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    file = models.FileField()
    upload_time = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Assignment(models.Model):
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    publish_time = models.DateTimeField(auto_now_add=True)
    due_time = models.DateTimeField()
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class AssignmentFile(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    uploader = models.ForeignKey(Student, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    file = models.FileField()
    upload_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class GradeRecord(models.Model):
    student = models.ForeignKey(Student)
    unit = models.ForeignKey(Unit)

    mark_assignment = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_quiz = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_presentation = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_mid_exam = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])
    mark_final_exam = models.FloatField(default=0, validators=[MinValueValidator(Decimal('0'))])

    @property
    def total_mark(self):
        return self.mark_assignment + self.mark_quiz + \
               self.mark_presentation + self.mark_mid_exam + self.mark_final_exam

LMS_Student/models.py
from django.db import models

# Create your models here.

LMS_Student/views.py
import re

from django.db.models import Q
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import TemplateView
from sendfile import sendfile

from LMS.mixins import QueryMixin
from LMS.models import Unit, Material, Assignment, AssignmentFile, GradeRecord
from LMS.views import BaseTimetableView
from LMS_Student.mixins import StudentMixin


class UnitQueryMixin(QueryMixin):
    def do_query(self, request, *args, **kwargs):
        unit = get_object_or_404(Unit, Q(student=self.request.user.student) & Q(pk=kwargs['unit_id']))

        self._unit = unit

    @property
    def unit(self):
        if not self._unit:
            raise Http404('Unknown unit.')

        return self._unit

    def get_context_data(self, **kwargs):
        ctx = super(UnitQueryMixin, self).get_context_data(**kwargs)

        ctx['unit'] = self._unit

        return ctx


class MaterialQueryMixin(UnitQueryMixin):
    def do_query(self, request, *args, **kwargs):
        super(MaterialQueryMixin, self).do_query(request, *args, **kwargs)

        material = get_object_or_404(Material, Q(unit=self.unit) & Q(pk=kwargs['material_id']))

        self._material = material

    @property
    def material(self):
        if not self._material:
            raise Http404('Unknown material.')

        return self._material

    def get_context_data(self, **kwargs):
        ctx = super(MaterialQueryMixin, self).get_context_data(**kwargs)

        ctx['material'] = self._material

        return ctx


class AssignmentQueryMixin(UnitQueryMixin):
    def do_query(self, request, *args, **kwargs):
        super(AssignmentQueryMixin, self).do_query(request, *args, **kwargs)

        assignment = get_object_or_404(Assignment, Q(unit=self.unit) & Q(pk=kwargs['assignment_id']))

        self._assignment = assignment

    @property
    def assignment(self):
        if not self._assignment:
            raise Http404('Unknown assignment.')

        return self._assignment

    def get_context_data(self, **kwargs):
        ctx = super(AssignmentQueryMixin, self).get_context_data(**kwargs)

        ctx['assignment'] = self._assignment

        return ctx


class UnitListView(StudentMixin, ListView):
    template_name = 'LMS_Student/unit.html'
    context_object_name = 'units'
    allow_empty = True

    def get_queryset(self):
        return self.request.user.student.enrolled_unit.all()


class EnrollListView(StudentMixin, ListView):
    template_name = 'LMS_Student/enroll.html'
    context_object_name = 'units'
    allow_empty = True
    model = Unit

    def post(self, request, *args, **kwargs):
        unit_id = request.POST.getlist('unit')
        units = Unit.objects.filter(pk__in=unit_id).all()
        self.request.user.student.enrolled_unit = units
        self.request.user.student.save()

        for u in units:
            grade, _ = GradeRecord.objects.get_or_create(student=self.request.user.student, unit=u)
        return HttpResponseRedirect(reverse_lazy('lms_stu:unit'))


class UnitInfoView(StudentMixin, UnitQueryMixin, DetailView):
    template_name = 'LMS_Student/unit_info.html'
    context_object_name = 'grade'

    def get_object(self, queryset=None):
        return GradeRecord.objects.get(unit=self.unit, student=self.request.user.student)


class MaterialListView(StudentMixin, UnitQueryMixin, ListView):
    template_name = 'LMS_Student/unit_material.html'
    context_object_name = 'materials'
    allow_empty = True

    def get_queryset(self):
        return Material.objects.filter(unit=self.unit)


class MaterialDownloadView(StudentMixin, MaterialQueryMixin, View):
    def get(self, request, *args, **kwargs):
        return sendfile(request, self.material.file.path, attachment=True)


class AssignmentListView(StudentMixin, UnitQueryMixin, ListView):
    template_name = 'LMS_Student/unit_assignment.html'
    context_object_name = 'assignments'
    allow_empty = True

    def get_queryset(self):
        return Assignment.objects.filter(unit=self.unit)


class AssignmentFileListView(StudentMixin, AssignmentQueryMixin, ListView):
    template_name = 'LMS_Student/unit_assignment_detail.html'
    context_object_name = 'files'
    allow_empty = True

    def get_queryset(self):
        return AssignmentFile.objects.filter(Q(assignment=self.assignment) & Q(uploader=self.request.user.student))


class AssignmentSubmitView(StudentMixin, AssignmentQueryMixin, CreateView):
    template_name = 'LMS_Student/unit_assignment_submit.html'
    model = AssignmentFile
    fields = ['name', 'file']

    def form_valid(self, form):
        # TODO: check due time
        submission = form.save(commit=False)
        submission.assignment = self.assignment
        submission.uploader = self.request.user.student
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('lms_stu:assignment_detail',
                            kwargs={'unit_id': self.unit.pk, 'assignment_id': self.assignment.pk})


class TimetableView(StudentMixin, BaseTimetableView):
    template_name = 'LMS_Student/timetable.html'

    def get_units(self):
        return self.request.user.student.enrolled_unit.all()


class PersonalInfoView(StudentMixin, TemplateView):
    template_name = 'LMS_Student/personal_info.html'

LMS_Student/templates/LMS_Student/enroll.html
{% extends 'LMS_Student/nav_base.html' %}

{% load i18n %}

{% block body_class %}stu stu-enroll{% endblock %}

{% block body %}
    <div class="row">
        Your course:
    </div>
    <div class="row">
        <legend>{{ user.student.course }}</legend>
    </div>
    <div class="row">
        <form method="POST">
            {% csrf_token %}
            <table class="table table-hover table-striped">
                <thead>
                <tr>
                    <th>Unit of study</th>
                    <th>Name</th>
                    <th>Year</th>
                    <th>Session</th>
                    <th>Location</th>
                    <th>CP</th>
                    <th><input type="checkbox" disabled/></th>
                </tr>
                </thead>
                <tbody>
                {% if units %}
                    {% for u in units %}
                        <tr>
                            <td>{{ u.code }}</td>
                            <td>{{ u.name }}</td>
                            <td>{{ u.year }}</td>
                            <td>{{ u.session }}</td>
                            <td>{{ u.location }}</td>
                            <td>{{ u.credit_point }}</td>
                            <td><input name="unit" value="{{ u.pk }}" type="checkbox" {% if u in user.student.enrolled_unit.all %}
                                       checked {% endif %}/>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
                </tbody>
            </table>
            <input type="submit" class="btn btn-primary pull-right" value="Submit"/>
        </form>
    </div>
{% endblock %}

LMS_Student/templates/LMS_Student/nav_base.html
{% extends "theme_bootstrap/subnav_base.html" %}

{% load i18n %}

{% block body_class %}student{% endblock %}

{% block subnav %}
<div class="panel panel-default">
{#    <div class="panel-heading"><strong>{% trans "Account Management" %}</strong></div>#}
    <div class="list-group">
        <a class="list-group-item stu-info" href="{% url 'lms_stu:home' %}">
            {% trans "Personal Info" %}
        </a>
        <a class="list-group-item stu-unit" href="{% url 'lms_stu:unit' %}">
            {% trans "My Units of Study" %}
        </a>
        <a class="list-group-item stu-timetable" href="{% url 'lms_stu:timetable' %}">
            {% trans "Timetable" %}
        </a>
        <a class="list-group-item stu-enroll" href="{% url 'lms_stu:enroll' %}">
            {% trans "Enroll" %}
        </a>
    </div>
</div>
{% endblock %}

LMS_Student/templates/LMS_Student/nav_unit.html
{% extends "theme_bootstrap/subnav_base.html" %}

{% load i18n %}

{% block body_class %}student{% endblock %}

{% block subnav %}
    <div class="panel panel-default">
        {#    <div class="panel-heading"><strong>{% trans "Account Management" %}</strong></div>#}
        <div class="list-group">
            <a class="list-group-item stu-unit-info" href="{% url "lms_stu:unit_info" unit.pk %}">
                {% trans "Unit Information" %}
            </a>
            <a class="list-group-item stu-unit-material" href="{% url 'lms_stu:material' unit.pk %}">
                {% trans "Materials" %}
            </a>
            <a class="list-group-item stu-unit-assignment" href="{% url 'lms_stu:assignment' unit.pk %}">
                {% trans "Assignments" %}
            </a>
        </div>
    </div>
{% endblock %}

LMS_Student/templates/LMS_Student/personal_info.html
{% extends 'LMS_Student/nav_base.html' %}

{% load i18n %}

{% block body_class %}stu stu-info{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <table class="table table-striped">
                    <tbody>
                    <tr>
                        <td>{% trans 'Name' %}</td>
                        <td>{{ user.first_name }} {{ user.last_name }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Gender' %}</td>
                        <td>{{ user.student.get_gender_display }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Year' %}</td>
                        <td>{{ user.student.year }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Course' %}</td>
                        <td>{{ user.student.course }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Start Date' %}</td>
                        <td>{{ user.student.start_date }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

LMS_Student/templates/LMS_Student/timetable.html
{% extends 'LMS_Student/nav_base.html' %}

{% load i18n %}

{% block body_class %}stu stu-timetable{% endblock %}

{% block body %}
    <div class="row">
        {% include 'timetable.html' %}
    </div>
{% endblock %}

LMS_Student/templates/LMS_Student/unit.html
{% extends 'LMS_Student/nav_base.html' %}

{% load i18n %}

{% block body_class %}stu stu-unit{% endblock %}

{% block body %}
    {% if units %}
        <div class="row">
            <ul class="list-group">
                {% for u in units %}
                    <a href="{% url "lms_stu:unit_info" u.pk %}"
                       class="list-group-item list-group-item-action">{{ u }}</a>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

LMS_Student/templates/LMS_Student/unit_assignment.html
{% extends 'LMS_Student/nav_unit.html' %}

{% load i18n %}

{% block body_class %}stu stu-unit-assignment{% endblock %}

{% block body %}
    {% if assignments %}
        <div class="row">
            <ul class="list-group">
                {% for a in assignments %}
                    <a href="{% url 'lms_stu:assignment_detail' unit.pk a.pk %}"
                       class="list-group-item list-group-item-action">{{ a }}</a>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

LMS_Student/templates/LMS_Student/unit_assignment_detail.html
{% extends 'LMS_Student/nav_unit.html' %}

{% load i18n %}

{% block body_class %}stu stu-unit-assignment{% endblock %}

{% block body %}
    <div class="row">
        <legend>Assignment Detail</legend>
    </div>
    <div class="row">
        Due time: {{ assignment.due_time }}
    </div>
    <div class="row">
        {% if assignment.description %}
            {{ assignment.description }}
        {% else %}
            No description.
        {% endif %}
    </div>
    <br/>
    <div class="row">
        <legend>Assignment Submissions</legend>
    </div>
    <div class="row">
        <a class="btn btn-primary"
           href="{% url 'lms_stu:assignment_submit' unit.pk assignment.pk %}">{% trans "New Submission" %}</a>
    </div>
    {% if files %}
        <div class="row">
            <ul class="list-group">
                {% for f in files %}
                    <a href=""
                       class="list-group-item list-group-item-action">{{ f }}</a>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

LMS_Student/templates/LMS_Student/unit_assignment_submit.html
{% extends 'LMS_Student/nav_unit.html' %}

{% load i18n %}
{% load bootstrap %}
{% load static %}

{% block body_class %}stu stu-unit-assignment{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-5">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|bootstrap }}
                <a class="btn btn-default pull-right"
                   href="{% url 'lms_stu:assignment_detail' unit.pk assignment.pk %}">{% trans "Cancel" %}</a>
                <button type="submit" class="btn btn-primary pull-right">{% trans "Submit" %}</button>
            </form>
        </div>
    </div>
{% endblock %}

LMS_Student/templates/LMS_Student/unit_info.html
{% extends 'LMS_Student/nav_unit.html' %}

{% load i18n %}

{% block body_class %}stu stu-unit-info{% endblock %}

{% block body %}
    {{ unit }}
    <div class="container-fluid">
        <div class="row">

            <div class="col-lg-6">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>{% trans 'Grades' %}</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>{% trans 'Assignment Mark' %}</td>
                        <td>{{ grade.mark_assignment }}</td>
                        <td>{% trans 'out of' %}</td>
                        <td>{{ unit.mark_assignment }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Quiz Mark' %}</td>
                        <td>{{ grade.mark_quiz }}</td>
                        <td>{% trans 'out of' %}</td>
                        <td>{{ unit.mark_quiz }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Presentation Mark' %}</td>
                        <td>{{ grade.mark_presentation }}</td>
                        <td>{% trans 'out of' %}</td>
                        <td>{{ unit.mark_presentation }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Mid Exam Mark' %}</td>
                        <td>{{ grade.mark_mid_exam }}</td>
                        <td>{% trans 'out of' %}</td>
                        <td>{{ unit.mark_mid_exam }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Final Exam Mark' %}</td>
                        <td>{{ grade.mark_final_exam }}</td>
                        <td>{% trans 'out of' %}</td>
                        <td>{{ unit.mark_final_exam }}</td>
                    </tr>
                    </tbody>
                    <tfoot>
                    <tr>
                        <th>{% trans 'Total Mark' %}</th>
                        <th>{{ grade.total_mark }}</th>
                        <th>{% trans 'out of' %}</th>
                        <th>{{ unit.total_mark }}</th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

LMS_Student/templates/LMS_Student/unit_material.html
{% extends 'LMS_Student/nav_unit.html' %}

{% load i18n %}

{% block body_class %}stu stu-unit-material{% endblock %}

{% block body %}
    {% if materials %}
        <div class="row">
            <ul class="list-group">
                {% for m in materials %}
                    <a href="{% url 'lms_stu:material_download' unit.pk m.pk %}"
                       class="list-group-item list-group-item-action">{{ m }}</a>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}